# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 08:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='telefone',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Telefone deve possuir o formato '+999999999' com menos de 15 digitos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
